title: blog.RustFest.EU
email: team@rustfest.eu
description: >
  A Community Rust conference for the Rusty folks all around Europe.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://blog.rustfest.eu" # the base hostname & protocol for your site
timezone: Europe/Zurich

# Build settings
markdown: kramdown

# Page Settings
owner: "asquera Event UG"
permalink: ":title"

collections:
  past_events:
    permalink: /:collection/:path
    # They have their own website!
    output: false


# social stuff:
metaKeywords: "rust, conf, rustfest, rustfesteu, conference, programming language, berlin"
twitter_username: rustfest
github_username:  rustfesteu
socialImageSrcTwitter: "/assets/favicons/logo.png"
socialImageSrcFacebook: "/assets/favicons/logo.png"


# mailinglist
mailchimp:
  server: asquera.us13.list-manage.com
  user: 7945052bc1ecc432bff53c079
  id: 5929ff51d6

exclude: ["/vendor"]
